# Generated by Django 4.0.1 on 2022-01-11 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferModel',
            new_name='Offer',
        ),
        migrations.CreateModel(
            name='OfferApplication',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el objeto.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue alterado el objeto.')),
                ('offer_application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_id', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
